window.StropaUI = (() => {
  const { products, byKey, money, escape: esc } = StropaData;
  const icon = name => `<svg viewBox="0 0 24 24" aria-hidden="true">${({ arrow: '<path d="M4 12h15m-6-6 6 6-6 6"/>', plus: '<path d="M12 4v16M4 12h16"/>', minus: '<path d="M4 12h16"/>', search: '<circle cx="10" cy="10" r="6.5"/><path d="m15 15 5 5"/>', check: '<path d="m5 12 4 4L19 6"/>' })[name]}</svg>`;
  const productLink = item => `#product/${item.id}/${item.color.id}`;
  const card = item => `<article class="product-card" data-price="${item.price}" data-key="${item.key}"><a class="product-photo" href="${productLink(item)}"><img src="${item.image}" alt="${item.name}, цвет ${item.color.name}" width="1200" height="900" loading="lazy"></a><div class="card-info"><a href="${productLink(item)}"><h3>${item.name}</h3><p>${item.volume} <span>·</span> ${item.color.name}</p></a><strong>${money(item.price)}</strong><button class="quick-add" type="button" data-add="${item.key}" aria-label="Добавить ${item.name}, ${item.color.name} в корзину">${icon('plus')}</button></div></article>`;
  const catalog = filters => `<section class="shop-hero"><div class="hero-copy"><h1>Город меняется.<br>Твой рюкзак — с тобой.</h1><p>Рюкзаки и сумки для ежедневных маршрутов.</p><button type="button" class="button button-dark" data-scroll-catalog>Выбрать свой ${icon('arrow')}</button></div><img src="assets/hero-wide.png" alt="Оливковый рюкзак СТРОПА на стальной скамье" width="1200" height="900" fetchpriority="high"></section><section class="catalog-section" id="catalog-section" aria-labelledby="catalog-title"><div class="catalog-title"><h2 id="catalog-title">На каждый день</h2><span id="product-count" aria-live="polite"></span></div><div class="catalog-tools"><div class="categories" aria-label="Категория">${[['all','Все'],['backpacks','Рюкзаки'],['slings','Сумки'],['totes','Шоперы']].map(([id,label])=>`<button type="button" data-category="${id}" aria-pressed="${filters.category===id}">${label}</button>`).join('')}</div><div class="search-sort"><label class="search-box">${icon('search')}<span class="sr-only">Найти модель</span><input type="search" id="catalog-search" placeholder="Найти модель" value="${esc(filters.search)}" autocomplete="off"></label><label class="sort-box"><span class="sr-only">Сортировка</span><select id="catalog-sort">${[['default','По умолчанию'],['price-asc','Сначала дешевле'],['price-desc','Сначала дороже']].map(([id,label])=>`<option value="${id}" ${filters.sort===id?'selected':''}>${label}</option>`).join('')}</select></label></div></div><div class="product-grid" id="product-grid"></div></section>`;
  const noResults = `<div class="empty-results"><h3>Такой модели пока нет.</h3><p>Попробуйте другое название или сбросьте фильтры.</p><button type="button" class="button" data-reset-filters>Показать все товары ${icon('arrow')}</button></div>`;
  const stepper = (value, key, max = 8) => `<div class="stepper"><button type="button" ${key?`data-cart-step="-1" data-key="${key}"`:'data-product-step="-1"'} aria-label="Уменьшить количество" ${value<=1?'disabled':''}>${icon('minus')}</button><output ${key?'':'id="product-quantity"'} aria-label="Количество">${value}</output><button type="button" ${key?`data-cart-step="1" data-key="${key}"`:'data-product-step="1"'} aria-label="Увеличить количество" ${value>=max?'disabled':''}>${icon('plus')}</button></div>`;
  const detail = (item, quantity) => `<div class="product-page"><div class="breadcrumbs"><a href="#catalog">Каталог</a><span>/</span><span>${item.name}</span></div><section class="product-detail"><div class="product-gallery"><img id="product-image" src="${item.image}" alt="${item.name}, цвет ${item.color.name}" width="1200" height="900"><div class="thumbnails">${item.colors.map(color=>`<button type="button" data-color="${color.id}" aria-label="Показать цвет ${color.name}" aria-pressed="${color.id===item.color.id}"><img src="assets/${item.id}-${color.id}.png" alt="${color.name}" width="1200" height="900"><span>${color.name}</span></button>`).join('')}</div></div><div class="product-description"><h1 id="product-title">${item.name}</h1><p class="product-intro">${item.description}</p><p class="product-price">${money(item.price)}</p><div class="color-choice"><p>Цвет: <strong>${item.color.name}</strong></p><div>${item.colors.map(color=>`<button type="button" data-color="${color.id}" style="--swatch:${color.hex}" aria-label="Цвет ${color.name}" aria-pressed="${color.id===item.color.id}"></button>`).join('')}</div></div><div class="spec-strip"><strong>${item.volume}</strong><span>${item.dimensions}</span><span>${item.weight}</span></div><div class="purchase-row">${stepper(quantity)}<button id="add-product" class="button" type="button" data-key="${item.key}">В корзину ${icon('plus')}</button></div><div class="accordions"><details open><summary>Детали</summary><p>${item.details}</p></details><details><summary>Доставка</summary><p>В этой демо-версии: пункт выдачи — 300 ₽, курьер — 500 ₽. От 10 000 ₽ — бесплатно. Фактическая доставка не выполняется.</p></details><details><summary>Уход</summary><p>Для модельного товара предусмотрена ручная очистка мягкой влажной тканью. Характеристики и рекомендации показаны для демонстрации интерфейса.</p></details></div></div></section><section class="inside-section"><h2>Внутри — всё нужное</h2><div>${item.inside.map((text,index)=>`<p><span>0${index+1}</span>${text}</p>`).join('')}</div></section><section class="related"><h2>Ещё для твоего маршрута</h2><div class="product-grid">${products.filter(p=>p.id!==item.id).slice(0,2).map(card).join('')}</div></section></div>`;
  const emptyCart = `<section class="empty-cart"><div class="empty-symbol" aria-hidden="true">${icon('plus')}</div><h1>Здесь начнётся<br>твой маршрут.</h1><p>Корзина пока пуста. Выберите рюкзак или сумку для своих планов.</p><a class="button" href="#catalog">Перейти в каталог ${icon('arrow')}</a></section>`;
  const cart = state => {
    const rows = StropaStore.rows(), shipping = StropaStore.delivery(state.delivery), subtotal = StropaStore.subtotal();
    if (!rows.length) return emptyCart;
    return `<section class="cart-page"><h1>Твой маршрут почти собран.</h1><div class="cart-layout"><div class="cart-main"><div class="cart-items">${rows.map(item=>`<article class="cart-row" data-key="${item.key}"><a href="${productLink(item)}"><img src="${item.image}" alt="${item.name}, ${item.color.name}" width="1200" height="900"></a><div class="cart-item-info"><a href="${productLink(item)}"><h2>${item.name}</h2></a><p>${item.color.name}</p>${stepper(item.quantity,item.key,item.stock)}</div><div class="cart-item-price"><strong>${money(item.price*item.quantity)}</strong><button type="button" data-remove="${item.key}" aria-label="Удалить ${item.name}, ${item.color.name}">Удалить</button></div></article>`).join('')}</div><form id="checkout-form" novalidate><h2>Оформление</h2><p class="form-note">Используйте тестовые данные. Оплата и отправка заказа не выполняются.</p><div class="form-grid">${[['customer','Имя','text','Например, Алексей'],['email','Email','email','name@example.com'],['city','Город','text','Например, Москва'],['address',state.delivery==='courier'?'Адрес доставки':'Адрес пункта выдачи','text','Улица, дом']].map(([name,label,type,placeholder])=>`<label>${label}<input name="${name}" type="${type}" value="${esc(state.draft[name]||'')}" placeholder="${placeholder}" required ${type==='text'?'minlength="2"':''} maxlength="150" autocomplete="off"></label>`).join('')}</div><fieldset class="delivery-options"><legend>Способ доставки</legend>${[['pickup','Пункт выдачи',300],['courier','Курьер',500]].map(([value,label,price])=>`<label><input type="radio" name="delivery" value="${value}" ${state.delivery===value?'checked':''}><span><strong>${label}</strong><small>${subtotal>=10000?'Бесплатно':money(price)}</small></span></label>`).join('')}</fieldset><p id="checkout-error" role="alert" class="form-error"></p><button id="place-order" type="submit" class="button">Собрать демо-заказ ${icon('arrow')}</button></form></div><aside class="order-summary" aria-labelledby="summary-title"><h2 id="summary-title">Заказ</h2><dl><div><dt>Товары (${StropaStore.count()})</dt><dd id="cart-subtotal">${money(subtotal)}</dd></div><div><dt>Доставка</dt><dd id="cart-delivery">${shipping?money(shipping):'Бесплатно'}</dd></div><div class="total"><dt>Итого</dt><dd id="cart-total">${money(subtotal+shipping)}</dd></div></dl><button type="button" class="button" id="start-checkout">Перейти к оформлению ${icon('arrow')}</button><p>Демо-магазин — списания денег нет.</p></aside></div></section>`;
  };
  const success = order => `<section class="order-success" id="order-success"><div class="success-mark">${icon('check')}</div><p class="order-number">${esc(order.number)}</p><h1>Демо-заказ собран.</h1><p>${esc(order.customer)}, весь путь покупки пройден. Заказ не отправлялся, деньги не списывались.</p><div class="receipt">${order.rows.map(item=>`<div><span>${item.name} · ${item.color.name} × ${item.quantity}</span><strong>${money(item.price*item.quantity)}</strong></div>`).join('')}<div><span>Доставка</span><strong>${order.shipping?money(order.shipping):'Бесплатно'}</strong></div><div class="receipt-total"><span>Итого</span><strong>${money(order.total)}</strong></div></div><a class="button" href="#catalog">Вернуться в каталог ${icon('arrow')}</a></section>`;
  const notFound = `<section class="empty-cart"><h1>Модель не найдена.</h1><p>Вернитесь в каталог и выберите одну из доступных моделей.</p><a class="button" href="#catalog">Открыть каталог ${icon('arrow')}</a></section>`;
  return { icon, card, catalog, noResults, detail, cart, success, notFound };
})();

