(()=>{
 const $=s=>document.querySelector(s),list=$('#document-list'),results=$('#results');
 const docs=IstokSamples.map(d=>({...d}));let selected=docs[0]?.id,busy=false,lastQuestion='',lastResult=null;
 const icon='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 3h9l5 5v13H5zM14 3v5h5M9 12h6M9 16h6"/></svg>';
 const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const paragraphs=text=>text.trim().split(/\n\s*\n/).map(t=>t.trim()).filter(Boolean);
 function status(text){$('#status').textContent=text;}
 function renderDocs(){list.innerHTML=docs.map(d=>`<div class="document-row ${selected===d.id?'selected':''}"><button type="button" data-document="${escape(d.id)}">${icon}<span><strong>${escape(d.name)}</strong><small>${paragraphs(d.text).length} абзацев</small></span></button><button class="remove-document" type="button" data-remove="${escape(d.id)}" aria-label="Удалить ${escape(d.name)}">×</button></div>`).join('');$('#document-count').textContent=docs.length+'/5';$('#search-button').disabled=busy||!docs.length;$('#file-input').disabled=busy;}
 function empty(){results.innerHTML=`<div class="empty"><h2>${docs.length?'Ответ начинается с источника.':'Добавьте документы'}</h2><p>${docs.length?'Введите вопрос — покажем подходящие фрагменты и место каждого в документе. Сейчас доступен локальный поиск, без генерации моделью.':'Загрузите TXT или MD либо откройте модельные документы. Для поиска нужен хотя бы один файл.'}</p>${docs.length?'<div class="suggestions"><button type="button" data-question="Когда отправляют заказы?">Когда отправляют заказы? ↗</button><button type="button" data-question="Кто выдаёт доступ новому сотруднику?">Кто выдаёт доступ новому сотруднику? ↗</button></div>':''}</div>`;}
 function source(id,paragraph){const d=docs.find(d=>d.id===id);if(!d)return;const citation=lastResult?.citations.find(c=>c.document_id===id&&c.paragraph===paragraph);selected=id;renderDocs();$('#source-pane').classList.remove('collapsed');$('#source-content').innerHTML=`<div class="source-title">${icon}<div><strong>${escape(d.name)}</strong><small>${paragraph?'Фрагмент '+paragraph:'Весь документ'}</small></div></div>${paragraphs(d.text).map((p,i)=>`<${p.startsWith('# ')?'h3':'p'} class="source-paragraph ${p.startsWith('# ')?'heading':''} ${citation&&p.includes(citation.quote)?'highlight':''}" data-paragraph="${i+1}">${escape(p.replace(/^# /,''))}</${p.startsWith('# ')?'h3':'p'}>`).join('')}`;if(innerWidth<=1000&&paragraph)$('#source-pane').scrollIntoView({behavior:'smooth',block:'start'});}
 function clearResults(){lastQuestion='';lastResult=null;empty();$('#source-content').innerHTML='<p class="source-placeholder">Откройте документ или ссылку под найденным фрагментом.</p>';}
 function renderResult(){const r=lastResult;results.innerHTML=`<div class="question-bubble">${escape(lastQuestion)}</div><h2 class="result-heading">${r.matched?'Найденные фрагменты':'Совпадений нет'}</h2><p class="result-note">${r.matched?'Совпадения в загруженных документах, без генерации ИИ.':'Попробуйте ключевые слова из документа. Отсутствие совпадений не доказывает отсутствие ответа.'}</p>${r.citations.map(c=>`<article class="citation"><p>${escape(c.quote)}</p><div class="citation-footer"><small>${c.number} · ${escape(c.document_name)} · абзац ${c.paragraph}</small><button type="button" data-source="${escape(c.document_id)}" data-paragraph="${c.paragraph}">Открыть источник ↗</button></div></article>`).join('')}`;}
 async function api(path,body){return IstokLocal.api(path,body);}
 async function search(){const question=$('#question').value.trim();if(!question||busy||!docs.length)return;busy=true;renderDocs();status('Ищем фрагменты…');try{const result=await api('ask',{question,documents:docs,mode:'search'});lastQuestion=question;lastResult=result;renderResult();if(result.citations.length)source(result.citations[0].document_id,result.citations[0].paragraph);else $('#source-content').innerHTML='<p class="source-placeholder">Нет найденных источников для этого вопроса.</p>';status('');}catch(e){status(e.name==='TimeoutError'?'Повторите поиск.':e.message==='Failed to fetch'?'Поиск выполняется в браузере. Повторите вопрос.':e.message);}finally{busy=false;renderDocs();}}
 $('#question-form').addEventListener('submit',e=>{e.preventDefault();search();});$('#question').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();search();}});
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.document)source(b.dataset.document);else if(b.dataset.source)source(b.dataset.source,Number(b.dataset.paragraph));else if(b.dataset.question){$('#question').value=b.dataset.question;search();}else if(b.dataset.remove&&!busy){const i=docs.findIndex(d=>d.id===b.dataset.remove);if(i>=0)docs.splice(i,1);selected=docs[0]?.id;clearResults();renderDocs();status('Документ удалён из сессии.');}});
 $('#load-samples').addEventListener('click',()=>{if(busy)return;docs.splice(0,docs.length,...IstokSamples.map(d=>({...d})));selected=docs[0].id;clearResults();renderDocs();status('Открыты модельные документы.');});
 $('#close-source').addEventListener('click',()=>$('#source-pane').classList.toggle('collapsed'));$('#about-ai').addEventListener('click',()=>$('#ai-dialog').showModal());$('#close-ai').addEventListener('click',()=>$('#ai-dialog').close());
 $('#file-input').addEventListener('change',async e=>{if(busy)return;const files=Array.from(e.target.files);if(files.length+docs.length>5){status('В одной сессии — до 5 документов. Удалите лишние файлы.');e.target.value='';return;}busy=true;renderDocs();status('Читаем документы…');try{const added=[];for(const f of files){if(f.size>2097152)throw Error('Файл больше 2 МБ: '+f.name);const bytes=new Uint8Array(await f.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));const result=await api('extract',{filename:f.name,content_base64:btoa(binary)});added.push({id:'upload-'+crypto.randomUUID(),name:result.document.name,text:result.document.text});}if([...docs,...added].reduce((sum,d)=>sum+d.text.length,0)>120000)throw Error('Общий объём текста — до 120 000 символов.');docs.push(...added);selected=added[0]?.id||selected;clearResults();status('Добавлено документов: '+added.length);}catch(error){status(error.message==='Failed to fetch'?'Поиск выполняется в браузере. Попробуйте другой TXT или MD.':error.message);}finally{busy=false;e.target.value='';renderDocs();}});
 renderDocs();empty();source(selected);status('Демо в браузере: документы и вопросы никуда не отправляются.');
})();
