window.BludoUI=(()=>{
 const esc=BludoEscape,money=BludoMoney;
 const paths={home:'<path d="m3 10 9-7 9 7v11h-7v-7h-4v7H3z"/>',cart:'<path d="M2 3h3l3 12h11l3-9H6M9 20h.01M18 20h.01"/><circle cx="9" cy="20" r="1"/><circle cx="18" cy="20" r="1"/>',order:'<rect x="5" y="3" width="14" height="18" rx="2"/><path d="M9 8h6M9 12h6M9 16h4"/>',pin:'<path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/>',arrow:'<path d="m9 5 7 7-7 7"/>',plus:'<path d="M12 5v14M5 12h14"/>',minus:'<path d="M5 12h14"/>',bowl:'<path d="M3 11h18c-1 6-5 10-9 10S4 17 3 11ZM9 3l2 5M14 3l-1 5"/>',chef:'<path d="M7 12a5 5 0 0 1-1-10 5 5 0 0 1 10 0 5 5 0 0 1 1 10v8H7zM7 16h10"/>',bike:'<circle cx="5" cy="17" r="4"/><circle cx="19" cy="17" r="4"/><path d="m5 17 5-9 4 9H5m5-9h7l2 9M8 5h4"/>',check:'<path d="m4 12 5 5L20 6"/>',truck:'<path d="M2 5h12v12H2ZM14 9h5l3 4v4h-8"/><circle cx="6" cy="19" r="2"/><circle cx="18" cy="19" r="2"/>'};
 const icon=name=>`<svg aria-hidden="true" viewBox="0 0 24 24">${paths[name]||paths.home}</svg>`;
 const heading=(title,subtitle='')=>`<h1>${title}</h1>${subtitle?`<p class="subheading">${subtitle}</p>`:''}`;
 function nav(active){const count=BludoStore.totals().count;return ['catalog','cart','order'].map((route,i)=>`<a href="#${route}" ${active===route?'aria-current="page"':''}>${icon(['home','cart','order'][i])}<span>${['Каталог','Корзина','Заказ'][i]}${route==='cart'&&count?` <b>${count}</b>`:''}</span></a>`).join('');}
 function card(p,featured=false){const qty=BludoStore.cart().find(r=>r.id===p.id)?.qty||0;return `<article class="food-card ${featured?'featured':''}"><button class="food-photo" type="button" data-detail="${p.id}" aria-label="Подробнее: ${esc(p.name)}"><img src="${p.image}" alt="${esc(p.name)}" width="1024" height="1024" ${featured?'fetchpriority="high"':'loading="lazy"'}></button><div class="food-info"><div><button class="food-name" type="button" data-detail="${p.id}">${esc(p.name)}</button><small>${p.weight}</small></div><strong>${money(p.price)}</strong><button class="add-food" data-add="${p.id}" type="button" aria-label="Добавить: ${esc(p.name)}">${qty?`<span>${qty}</span>`:icon('plus')}</button></div></article>`;}
 function catalog({category,search,address}) {
  const query=search.toLocaleLowerCase('ru');const products=BludoData.products.filter(p=>(category==='Все'||p.category===category)&&`${p.name} ${p.description}`.toLocaleLowerCase('ru').includes(query));
  const featured=category==='Все'&&!search?products[0]:null;
  return `<button class="address-select" data-address type="button">${icon('pin')}<span>${esc(address||'Куда доставить?')}</span>${icon('arrow')}</button>${heading('Обед по твоим правилам')}<label class="search-field">${icon('search')}<span class="sr-only">Найти блюдо</span><input id="food-search" type="search" placeholder="Найти блюдо" value="${esc(search)}" autocomplete="off"></label><div class="categories" aria-label="Категории блюд">${BludoData.categories.map(c=>`<button type="button" data-category="${c}" aria-pressed="${c===category}">${c}</button>`).join('')}</div><div id="food-list">${products.length?`${featured?card(featured,true):''}<div class="food-grid">${products.filter(p=>p!==featured).map(p=>card(p)).join('')}</div>`:`<section class="empty"><h2>Такого блюда пока нет</h2><p>Попробуйте другое название или сбросьте поиск.</p><button type="button" data-clear-search>Показать всё меню</button></section>`}</div>`;
 }
 function totals(){const t=BludoStore.totals();return `<dl class="cart-totals"><div><dt>Товары</dt><dd>${money(t.subtotal)}</dd></div><div><dt>Доставка</dt><dd>${t.delivery?money(t.delivery):'Бесплатно'}</dd></div><div class="grand-total"><dt>Итого</dt><dd id="cart-total">${money(t.total)}</dd></div></dl>`;}
 function cart(){const rows=BludoStore.cart(),count=BludoStore.totals().count;if(!rows.length)return `${heading('Корзина')}<section class="empty"><div class="empty-icon">${icon('cart')}</div><h2>Выберите что-нибудь вкусное</h2><p>Блюда из каталога появятся здесь.</p><a class="primary" href="#catalog">Открыть меню</a></section>`;return `${heading('Корзина',`Порций: ${count}`)}<div class="cart-rows">${rows.map(r=>{const p=BludoStore.product(r.id);return `<article class="cart-row" data-id="${r.id}"><img src="${p.image}" alt="${esc(p.name)}" width="1024" height="1024"><div class="cart-copy"><h2>${p.name}</h2><p>${p.weight}</p><strong>${money(p.price*r.qty)}</strong><button class="remove-food" data-remove="${r.id}" type="button">Убрать</button></div><div class="stepper"><button data-step="-1" data-id="${r.id}" type="button" aria-label="Уменьшить: ${p.name}">${icon('minus')}</button><output>${r.qty}</output><button data-step="1" data-id="${r.id}" type="button" ${r.qty===9?'disabled':''} aria-label="Увеличить: ${p.name}">${icon('plus')}</button></div></article>`;}).join('')}</div><p class="delivery-rule">${icon('truck')}<span>Доставка 190 ₽ · бесплатно от 1 500 ₽</span></p>${totals()}<a class="primary checkout-link" href="#checkout">Оформить заказ</a>`;}
 function checkout(address){if(!BludoStore.cart().length)return cart();return `${heading('Оформление','Демонстрационный заказ')}<form id="checkout-form" class="checkout-form"><label>Имя<input name="name" required minlength="2" maxlength="80" autocomplete="given-name" placeholder="Как к вам обращаться"></label><label>Телефон<input name="phone" required type="tel" inputmode="tel" maxlength="20" autocomplete="tel" placeholder="+7 999 123-45-67"></label><label>Адрес доставки<input name="address" required minlength="5" maxlength="160" autocomplete="street-address" value="${esc(address)}" placeholder="Улица, дом, квартира"></label><label>Комментарий<textarea name="comment" rows="2" maxlength="300" placeholder="Например, домофон 12"></textarea></label><div class="payment-mode"><strong>Способ оплаты</strong><p>Демо-оформление без списания денег</p></div>${totals()}<p class="demo-disclosure">Это проект портфолио. Заказ сохранится только в этом браузере; ресторан и курьер его не получат. Телефон и комментарий не сохраняются.</p><p id="checkout-error" role="alert"></p><button class="primary" type="submit">Создать демо-заказ</button></form>`;}
 function order(){const o=BludoStore.order();if(!o)return `${heading('Мой заказ')}<section class="empty"><div class="empty-icon">${icon('order')}</div><h2>Здесь появится ваш заказ</h2><p>Выберите блюда и завершите демо-оформление.</p><a class="primary" href="#catalog">Выбрать блюда</a></section>`;const notes=BludoData.stageNotes;return `${heading(o.stage===0?'Заказ принят':BludoData.stages[o.stage],'Демонстрационная доставка')}<div class="progress-icons">${['bowl','chef','bike','check'].map((n,i)=>`<div class="${i<=o.stage?'active':''}">${icon(n)}<small>${BludoData.stages[i]}</small></div>`).join('')}</div><ol class="timeline">${BludoData.stages.map((s,i)=>`<li class="${i===o.stage?'current':''} ${i<o.stage?'complete':''}"><strong>${s}</strong><span>${notes[i]}</span></li>`).join('')}</ol><div class="order-summary"><div class="order-thumbs">${o.items.slice(0,2).map(r=>`<img src="${BludoStore.product(r.id).image}" alt="${BludoStore.product(r.id).name}" width="1024" height="1024">`).join('')}</div><div><strong>${o.items.map(r=>`${BludoStore.product(r.id).name}${r.qty>1?' × '+r.qty:''}`).join(' + ')}</strong><small>${esc(o.id)}</small></div><b>${money(o.total)}</b></div><div class="order-address">${icon('pin')}<div><small>Адрес доставки</small><p>${esc(o.address)}</p></div></div>${o.stage<3?'<button class="primary" data-advance type="button">Следующий этап демо</button>':'<a class="primary" href="#catalog">Заказать ещё</a>'}`;}
 return{icon,nav,catalog,cart,checkout,order};
})();
